version: "3.3"
services:

  auth:
    image: 'authprod:${TAG-latest}'
    container_name: auth-production
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}/auth
      - PORT
      - BASE_PATH=/auth
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-auth-http.rule=PathPrefix(`/auth`)
      - traefik.http.services.${STACK_NAME?Variable not set}-auth.loadbalancer.server.port=${PORT}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not
          set}-auth-http.rule=PathPrefix(`/auth`)
        - traefik.http.services.${STACK_NAME?Variable not
          set}-auth.loadbalancer.server.port=${PORT}
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
